apiVersion: apps/v1
kind: Deployment
metadata:
   name: plasma
spec:
   replicas: 1
   selector:
     matchLabels:
       app: plasma
   template:
     metadata:
       labels:
         app: plasma
     spec:
       containers:
       - name: plasma
         image: icr.io/yogi18/plasma_b6
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
